### ISSUE TITLE
docker-compose.yml moved?

### ISSUE THREAD

**Issue by jblakley** [scanner-research/scanner#113]
It seems like instructions are now wrong in README.md. It says: 

>> wget http://raw.githubusercontent.com/scanner-research/scanner/master/docker-compose.yml

But, I think that it is now:

>> wget http://raw.githubusercontent.com/scanner-research/scanner/master/docker/docker-compose.yml

If so, then I'm also having a problem with the gpu pull:

>> nvidia-docker-compose pull gpu

Gives error of:

Traceback (most recent call last):
  File "/usr/bin/nvidia-docker-compose", line 55, in <module>
    resp = request.urlopen('http://{0}/docker/cli/json'.format(args.nvidia_docker_host)).read().decode()
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1244, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 111] Connection refused>

I am running on google cloud platform with NVIDIA P100 attached. The CPU instructions work fine.

**Comment by apoms** [comment]
Hi Jim,

I just finished simplifying our installation process from source and haven't updated the documentation to match. I'll respond back once everything's stabilized again.

**Comment by apoms** [comment]
Hi Jim,

Will have the documentation updated in 2-3 hours (you are right in that the compose file moved).

For the second issue, nvidia-docker was updated in a way that breaks nvidia-docker-compose. Can you try building with version 1.0 of nvidia-docker? That can be found here https://github.com/NVIDIA/nvidia-docker/tree/1.0

**Comment by AKSHAYUBHAT** [comment]
Using docker-compose with nvidia-docker2 requires a minor change add 
`"default-runtime": "nvidia"` to file /etc/docker/daemon.json [1] After this you can just use 
docker-compose instead of nvidia-docker-compose. 

1. https://github.com/NVIDIA/nvidia-docker/issues/568

**Comment by apoms** [comment]
@jblakley Everything should be updated now. Please let me know if there is anything else I can do on my end. Thanks for trying to get it running from your side!

**Comment by jblakley** [comment]
Thanks Alex and Akshay. Akshay's fix seemed to work. I didn't try using version 1 of nvidia-docker.

**Comment by jblakley** [comment]
This works now.
