### ISSUE TITLE
Syntax error in util.py

### ISSUE THREAD

**Issue by jblakley** [scanner-research/scanner#116]
Got the following error in both the latest gpu and cpu docker containers. It didn't occur on the older version of the cpu container (still trying to get the gpu container to work).

root@75cb001bbeee:/opt/scanner# python examples/apps/face_detection/main.py star_wars_heros.mp4
Traceback (most recent call last):
  File "examples/apps/face_detection/main.py", line 2, in <module>
    from scannerpy.stdlib import pipelines
  File "/usr/local/lib/python2.7/dist-packages/scannerpy/stdlib/pipelines.py", line 8, in <module>
    from scannerpy.stdlib.util import temp_directory, download_temp_file
  File "/usr/local/lib/python2.7/dist-packages/scannerpy/stdlib/util.py", line 37
    https://youtu.be/SHoHdkUw-Is  '--restrict-filenames --get-filename'
         ^
SyntaxError: invalid syntax

**Comment by apoms** [comment]
@jblakley Pushed a fix for that. Apologies, that was some in progress code which snuck into a commit. Let me know if it is working now!

**Comment by jblakley** [comment]
@apoms  The docker CPU container seems to be working. Trying the GPU container now.

**Comment by jblakley** [comment]
Closing this one -- still working on GPU container but I think this specific problem is fixed.
