### ISSUE TITLE
Preferred reference for citation

### ISSUE THREAD

**Issue by AKSHAYUBHAT** [scanner-research/scanner#122]
Is there a reference paper, arxiv preprint that I can cite? Or should I use github url? 

Thanks,

**Comment by kayvonf** [comment]
Github URL is likely the most appropriate citation for Scanner at this time, but it might depend on context.  Could you tell us more about the citation.  Is Scanner being used in a publication?

**Comment by AKSHAYUBHAT** [comment]
Right now I am citing it for SysML workshop at Stanford, so its not archival. But I plan to later convert the paper for a confernece/journal. I will check back again then and will use github link for now.
