### ISSUE TITLE
Building Scanner for CPU -- build looking for CUDA

### ISSUE THREAD

**Issue by jblakley** [scanner-research/scanner#124]
Since I couldn't get the container fully working, I tried building scanner for CPU from scratch. Got all the dependencies to install but the scanner build is failing. Its looking for CUDA which is irrelevant for CPU build. Here's the output of cmake:

-- No build type selected, defaulting to Release
CMake Error at /usr/share/cmake-3.5/Modules/FindCUDA.cmake:617 (message):
  Specify CUDA_TOOLKIT_ROOT_DIR
Call Stack (most recent call first):
  cmake/Dependencies.cmake:18 (find_package)
  CMakeLists.txt:67 (include)

-- Configuring incomplete, errors occurred!
See also "/root/git/scanner/build/CMakeFiles/CMakeOutput.log".
root@instance-1-ubuntu-skl-1:~/git/scanner/build# cat outfile.txt
-- No build type selected, defaulting to Release
CMake Error at /usr/share/cmake-3.5/Modules/FindCUDA.cmake:617 (message):
  Specify CUDA_TOOLKIT_ROOT_DIR
Call Stack (most recent call first):
  cmake/Dependencies.cmake:18 (find_package)
  CMakeLists.txt:67 (include)

-- Configuring incomplete, errors occurred!
See also "/root/git/scanner/build/CMakeFiles/CMakeOutput.log".

I tried installing CUDA anyway and setting CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda but it still failed the same way.

**Comment by willcrichton** [comment]
Right now, you have to explicitly disable the BUILD CUDA flag.
```
cmake -D BUILD_CUDA=Off ..
```

**Comment by jblakley** [comment]
That worked -- successfully built and could run shot example. Still trying faces example.
