### ISSUE TITLE
Add a "stateful" attribute to Op declarations

### ISSUE THREAD

**Issue by apoms** [scanner-research/scanner#14]
Currently, the system must spawn a copy of every Op in the user specified pipeline for each kernel instance as any of them may be _logically_ stateful -- previous elements fed into that kernel instance may effect the results of any future element fed into the kernel. However, in many cases, kernels are only "physically" stateful -- they keep state in order to amortize working set allocations or large read only buffers (such as the parameters in a DNN). If the system understood when an Op was not _logically_ stateful, it could share instances of that Op across pipelines, reducing memory footprint.

**Comment by willcrichton** [comment]
How would physically stateful ops be shared across pipelines? In the DNN example, you can't use Caffe concurrently by multiple threads.

**Comment by apoms** [comment]
They would be time-multiplexed. Currently, we are forced to spawn multiple instances of the DNN kernel per GPU if we had multiple pipelines per GPU but we really can only effectively run one (assuming the DNN saturates the GPU, which it should). Think about it as the kernel being a "resource" that work items from different pipelines are scheduled onto.

**Comment by apoms** [comment]
Addressed by `bounded_state` and `unbounded_state` on Op.
