### ISSUE TITLE
deps.sh OpenPose build issue

### ISSUE THREAD

**Issue by jblakley** [scanner-research/scanner#143]
Building on GCP with V100 GPU. Following error running deps.sh during OpenPose install.

...

/root/git/scanner/thirdparty/install/include/boost/python/detail/is_auto_ptr.hpp:17:1: note: in expansion of macro ‘BOOST_PYTHON_IS_XXX_DEF’
 BOOST_PYTHON_IS_XXX_DEF(auto_ptr, std::auto_ptr, 1)
 ^
In file included from /usr/include/c++/5/condition_variable:43:0,
                 from /root/git/scanner/thirdparty/build/hwang/./hwang/decoder_automata.h:21,
                 from /root/git/scanner/thirdparty/build/hwang/hwang/hwang_python.cpp:4:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
[ 57%] Built target hwang_source
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Installing hwang failed!

**Comment by apoms** [comment]
There's been lots of changes since this issue. If it's still a problem, feel free to reopen.
