### ISSUE TITLE
Scanner hangs after call to gRPC

### ISSUE THREAD

**Issue by szekany** [scanner-research/scanner#146]
I've been using Scanner for a few weeks, but (seemingly) out of the blue I'm getting an error when running the examples:

`Master did not receive heartbeat in 50000ms. Shutting down.`

It appears that this is related to gRPC/protobuf. Line 378 in database.py gets called but never returns:

`self._master.Ping(self.protobufs.Empty())`

I've tried reinstalling Scanner and all the dependencies (using the deps.sh script), but I'm still getting the same error. Anyone ever seen this before or have any suggestions on what to try next?

**Comment by szekany** [comment]
Not sure what the issue was here, but I resolved it by doing a complete reinstall of Ubuntu + Scanner.

**Comment by apoms** [comment]
Hey @szekany, did this happen consistently or just randomly? 

My suspicion is that for some reason the Ping call is getting stuck waiting for a response and, since there is no timeout, never finishes. I'll try to fix that.

**Comment by szekany** [comment]
Yeah, it seemed to be happening consistently (as in, I could never get the example to finish). Really weird.

**Comment by apoms** [comment]
@szekany I just added timeouts to most of the python GRPC calls. Hopefully that should solve the issue.

**Comment by szekany** [comment]
Cool, thanks!
