### ISSUE TITLE
Running Face Detection Example -- Error: requested kernel with device type GPU but no such kernel exists.

### ISSUE THREAD

**Issue by jblakley** [scanner-research/scanner#147]
Environment GCP 4xCore, 1 P100 GPU Ubuntu 16.04 -- on host -- Cuda 9.0/CuDNN 7.0
Latest GPU docker container (2/21/2018)
nvidia-smi works fine on both host and container
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.30                 Driver Version: 390.30                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   33C    P0    26W / 250W |     10MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
Running Face Detection Example -- (same error with shot example).

root@c750f8128054:/opt/scanner# python examples/apps/face_detection/main.py star_wars_heros.mp4 # short file
Detecting faces in movie star_wars_heros.mp4
Ingesting video into Scanner ...
Detecting faces...
Downloading https://storage.googleapis.com/scanner-data/nets/caffe_facenet/facenet_deploy.prototxt to /root/.scanner/resources/facenet_deploy.prototxt...
Downloading https://storage.googleapis.com/scanner-data/nets/caffe_facenet/facenet_deploy.caffemodel to /root/.scanner/resources/facenet_deploy.caffemodel...
Downloading https://storage.googleapis.com/scanner-data/nets/caffe_facenet/facenet_templates.bin to /root/.scanner/resources/facenet_templates.bin...
E0221 20:22:10.054975   203 dag_analysis.cpp:220] Op FacenetInput at index 1 requested kernel with device type GPU but no such kernel exists.
Traceback (most recent call last):
  File "examples/apps/face_detection/main.py", line 28, in <module>
    movie_name + '_bboxes')
  File "/usr/local/lib/python2.7/dist-packages/scannerpy/stdlib/pipelines.py", line 111, in detect_faces
    pipeline_instances_per_node=pipeline_instances)
  File "/usr/local/lib/python2.7/dist-packages/scannerpy/database.py", line 1153, in run
    raise ScannerException(job_status.result.msg)
scannerpy.common.ScannerException: Op FacenetInput at index 1 requested kernel with device type GPU but no such kernel exists.

**Comment by willcrichton** [comment]
Can you clarify what's the specific command used to create/enter the Docker container?

**Comment by apoms** [comment]
Hi Jim, I made a small update to our dependency build process but forgot to update the base docker image we use for holding our dependencies. That base image is rebuilding right now and the issue should be fixed after it's rebuilt. I'll let you know when that's done (~1-2 hours).

**Comment by jblakley** [comment]
Will, started the container with:

docker-compose pull gpu &&
nvidia-docker-compose run --service-ports gpu /bin/bash

**Comment by apoms** [comment]
The Docker images have been updated. @jblakley: let me know if the issue is resolved.

**Comment by jblakley** [comment]
Alex, same issue. 
>>  docker-compose pull gpu
Pulling gpu (scannerresearch/scanner:gpu)...
gpu: Pulling from scannerresearch/scanner
Digest: sha256:8ea310aec0831b550ebce34ba5dc7e91e94dcceb17a7db30ffdc0dbbdf8014ec
Status: Image is up to date for scannerresearch/scanner:gpu

>> nvidia-docker-compose run --service-ports gpu /bin/bash

>> python examples/apps/shot_detection/shot_detect.py star_wars_heros.mp4
Detecting shots in movie star_wars_heros.mp4
Your Scanner configuration file does not exist. Create one? [Y/n] Y
Wrote Scanner configuration to /root/.scanner.toml
Loading movie into Scanner database...
Time: 0.1s
Number of frames in movie: 972
Computing a color histogram for each frame...
E0222 16:56:17.675937    29 dag_analysis.cpp:220] Op Histogram at index 1 requested kernel with device type GPU but no such kernel exists.
Traceback (most recent call last):
  File "examples/apps/shot_detection/shot_detect.py", line 191, in <module>
    main(sys.argv[1])
  File "examples/apps/shot_detection/shot_detect.py", line 109, in main
    [hists_table] = db.run(bulk_job, force=True)
  File "/usr/local/lib/python2.7/dist-packages/scannerpy/database.py", line 1153, in run
    raise ScannerException(job_status.result.msg)
scannerpy.common.ScannerException: Op Histogram at index 1 requested kernel with device type GPU but no such kernel exists.


Could it be some discrepancy between host and container?

**Comment by jblakley** [comment]
Here is the file that I used to configure the instance.
[scannerconfig-full-ubuntu-docker-gpu-anon.txt](https://github.com/scanner-research/scanner/files/1749202/scannerconfig-full-ubuntu-docker-gpu-anon.txt)

**Comment by apoms** [comment]
@jblakley: Just confirmed that the issue you are facing should be fixed. Sorry for the run around; the issue had to due with a misconfiguration when building the GPU docker image that built Scanner without CUDA support.

**Comment by jblakley** [comment]
That fixed it!
