### ISSUE TITLE
Make Scanner Distributed Again

### ISSUE THREAD

**Issue by apoms** [scanner-research/scanner#15]

**Comment by willcrichton** [comment]
We also need to explore how to setup a cluster when the nodes are wrapped in Docker containers. Right now you can only use Docker for quickly experimenting on a single node, but can't use it to scale out (or at least, we haven't tried). It might Just Work™, but it might need some fussing with the Docker network configuration or god knows what else. Regardless, there should be a documented process for setting up a cluster using both a manual install and the Docker image.

**Comment by apoms** [comment]
Closed by 2cebc4eef1c2420a625737e47854a8a187966e92
