### ISSUE TITLE
Possible to use GPU acceleration with Tensorflow?

### ISSUE THREAD

**Issue by szekany** [scanner-research/scanner#150]
Hi, quick question: I notice the Tensorflow object detection example uses CPU for inference. I'm trying to figure out if it's possible to use GPU acceleration for a Python kernel that uses Tensorflow?

(I think the answer is yes, based on this [pull request](https://github.com/scanner-research/scanner/pull/102) but I'm having trouble figuring out how this should work since it appears that master.cpp always sets the input and output columns to CPU-only.)

**Comment by willcrichton** [comment]
Yes it is possible. Python kernels have inputs/outputs as CPU only since (to our knowledge) there are no Python libraries which can take GPU memory directly as input, including TensorFlow. However, this doesn't preclude TensorFlow from doing its own GPU transfers/processing, which we use quite frequently.

**Comment by szekany** [comment]
OK, thanks! So does that mean I'd write and register three Python kernels to do an operation: an input that's CPU-only, an intermediate that uses GPU, and an output that's CPU-only? Or is it possible to do it all in one Python kernel? (Sorry if this seems like an obvious question, I'm still learning the internals of Scanner).

**Comment by willcrichton** [comment]
It's all good! Both of those are possible. What you should be able to do (I think) is register a Python kernel with CPU inputs/outputs, but whose device is a GPU. This ensures the inputs/outputs are on the CPU device, but the kernel will be scheduled appropriately to a single GPU.

The latter part (scheduling the kernel onto a specific GPU) I'm less sure as to how functional that is. Theoretically, it should work, and the device id of the GPU should be passed in to the Python kernel constructor, which should then be provided to TensorFlow so it can map operations to its GPU accordingly. @apoms can you confirm?

**Comment by apoms** [comment]
As @willcrichton mentioned, it's not really possible to provide GPU inputs to a Python kernel, but you can still use GPUs with Python kernels! Just like with the C++ kernels, you can indicate that the Python kernel requires a GPU resource. For example,

```python
db.register_python_kernel('MyKernel', DeviceType.GPU, kernel_path)
```

All the inputs for the python kernel will come in on CPU memory and all the outputs should be in CPU memory as well, but the Python kernel will be assigned a GPU. To determine which GPU this is, all Python kernels receive a config object when their `__init__` function is called that lists the devices they were assigned. This config object looks like this: https://github.com/scanner-research/scanner/blob/master/python/scannerpy/kernel.py#L3. You can access the devices by accessing the `devices` field, such as:

```python
class MyKernel(Kernel):
    def __init__(self, config, protobufs):
        self.config = config
        self.protobufs = protobufs
        
        # Grab the first assigned device (for GPU kernels, there is always only one device)
        handle = config.devices[0]
        # The DeviceType should be GPU
        assert handle.device == DeviceType.GPU
        # Print the GPU id
        print(handle.device_id)
```

The class for `handle` is DeviceHandle (https://github.com/scanner-research/scanner/blob/master/python/scannerpy/common.py#L26).

We also have a `TensorFlowKernel` that does some basic TF setup, but it could be improved (for example, it doesn't automatically setup the graph you specify to run on the assigned GPU). That's here: https://github.com/scanner-research/scanner/blob/master/python/scannerpy/stdlib/kernel.py

**Comment by szekany** [comment]
Thanks! One last question, when I specify DeviceType.GPU when calling register_python_kernel() with the object_detector_tensorflow example (in main.cpp:216), I get an error:

`Op ObjDetect at index 2 requested kernel with device type CPU but no such kernel exists.
`

Is there something else that I need to change to specify that this is a GPU kernel?

**Comment by apoms** [comment]
You also need to specify that the Op should use a GPU kernel (L219):
```python
        objdet_frame = db.ops.ObjDetect(frame = strided_frame, device=DeviceType.GPU)
```

We should default to using whatever kernel type is available if the device was not specified (in this case, it should automatically set `device=DeviceType.GPU`).

**Comment by szekany** [comment]
OK, when I make that change it's getting past that error (yay!), but now I get a segfault from NVIDIAVideoDecoder::configure (boo):

```
Thread 251 "python" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffeb67fc700 (LWP 26810)]
0x00007fffe73898b1 in scanner::internal::NVIDIAVideoDecoder::configure(scanner::FrameInfo const&) [clone .part.18] [clone .constprop.64] () from /home/szekany/.local/lib/python2.7/site-packages/scannerpy/libscanner.so

```
Any idea why that would happen? Some kind of conflict between the video decoder and Tensorflow?

**Comment by apoms** [comment]
This should not be happening! Let me look into it...

**Comment by szekany** [comment]
Thanks for looking into it! If it matters, I'm using CUDA 9.0 (necessary for latest version of Tensorflow - it made more sense to make slight changes to Scanner and dependencies than to downgrade Tensorflow).

It's possible this doesn't happen when using CUDA 8.0. I'll try that later tonight or early tomorrow and report back.

**Comment by apoms** [comment]
Yeah, I am able to run the tf object detection using my build of Scanner, which uses CUDA 8.0. We have had issues with the decoder on CUDA 9.0, so that might be it. 

Proper support for CUDA 9.0 is a definite todo though!

**Comment by szekany** [comment]
Alright, I'll try downgrading to CUDA 8.0. Hopefully that will fix it!

**Comment by szekany** [comment]
Just did a reinstall of Scanner, its dependencies, CUDA 8.0, and TF 1.4, and the object_detection_tensorflow example now runs with GPU support (verified with nvidia-smi). Thanks for all the help!

FWIW, I do get a bunch of errors at the very end from TF about CUDA thread contexts... but it doesn't seem to affect the output:
`2018-03-21 11:36:13.602339: E tensorflow/stream_executor/event.cc:33] error destroying CUDA event in context 0x7f4c4fe76a20: CUDA_ERROR_INVALID_CONTEXT
`

**Comment by apoms** [comment]
This has to do with tensorflow not wanting anyone else to use the GPU, but I don't think it causes any issues. 

Closing as resolved.
