### ISSUE TITLE
AWS V100 Issue

### ISSUE THREAD

**Issue by jblakley** [scanner-research/scanner#152]
Running shot detection sample app in gpu container on AWS V100 (P3) instance generated:

OpenCV Error: Gpu API call (invalid device function) in split, file /opt/scanner-base/thirdparty/build/opencv/modules/cudev/include/opencv2/cudev/grid/detail/split_merge.hpp, line 241
terminate called after throwing an instance of 'cv::Exception'
  what():  /opt/scanner-base/thirdparty/build/opencv/modules/cudev/include/opencv2/cudev/grid/detail/split_merge.hpp:241: error: (-217) invalid device function in function split

Works fine on GCP P100 instance and AWS M60 instance.

nvidia-smi output:

Wed Mar 28 13:26:02 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.30                 Driver Version: 390.30                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   32C    P0    36W / 300W |   1020MiB / 16160MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

**Comment by apoms** [comment]
Hi Jim,

I believe this issue is due to our outstanding need to add support for CUDA 9.0 (Volta requires CUDA 9.0 I believe). I’ll take a look into it tomorrow! 

Alex

**Comment by apoms** [comment]
Update: I am switching up our Docker build flow to support multiple versions of CUDA (8.0, 9.1, etc). This will fix the issues you are seeing with the V100s. I'll let you know when this transition is complete. I expect I'll finish it by Monday.

**Comment by apoms** [comment]
Hi @jblakley, this turned out to be a lot more effort than I thought (very involved interdependencies between CUDA 9.1, CMake, OpenCV, and Boost) but we now provide docker images for CUDA 8.0 and CUDA 9.1. If you use the usual docker-compose flow (which is in the README) it will default to the CUDA 9.1 docker image, which should fix your V100 issue.

Let me know if that works and thanks for waiting!

**Comment by jblakley** [comment]
Alex, I think something broke separate from this issue. If you want, I can open a separate issue but its blocking me from checking this one. Now when I run the shot example, I get:

root@98d5a32243da:/opt/scanner# python examples/apps/shot_detection/shot_detect.py /root/MediaAssets/star_wars_heros.mp4
Traceback (most recent call last):
  File "examples/apps/shot_detection/shot_detect.py", line 1, in <module>
    from scannerpy import Database, DeviceType, Job, BulkJob
ImportError: cannot import name BulkJob


Let me know if you want this a new issue.

**Comment by apoms** [comment]
That was an issue with an API update we made which we didn't change for the examples. Should be fixed now!

**Comment by jblakley** [comment]
That seems to have fixed it! Thanks. Have run shot_detection, face_detection and optical_flow on AWS P3 instance. Now I need to figure out what changed in the API so I can modify my test scripts.
