### ISSUE TITLE
Make install procedure

### ISSUE THREAD

**Issue by willcrichton** [scanner-research/scanner#17]
Need to be able to `make install` Scanner build into a directory, should use standard CMake install mechanisms. Should consider how to handle both the C++ library as well as the Python package (should they be distributed in the same directory? As a pip package?). Anything that relies on knowing the Scanner path (e.g. loading pb2.py files in database.py) should be changed to reflect this.

**Comment by sdulloor** [comment]
Distributing scanner as a pip package would be best, IMO.

**Comment by willcrichton** [comment]
As of 50ebde65303e5e8158f0fe54c7280fe6f3bbe9e2, we now have a preliminary pip package: https://pypi.python.org/pypi/scannerpy

The way it works is that we prebuild and ship the generated files (protobuf files, shared library) along with everything in the `python` directory. Will eventually ship the headers, need to add those too. The problem with this is that you can only use the package if you have all the same libraries and versions used by `libscanner.so`, so it's heavily dependent on a lot of tricky configuration. Right now this is solved with Docker, but not sure if there's a better way to do it.

**Comment by willcrichton** [comment]
As of f50fd2575059ca4b4cf5d361358d124e92a4a4db, this is finalized. Development users should run `scripts/dev-setup.sh` from the root of the Scanner repo and should put this into your shell config: 
```bash
export PYTHONPATH=${SCANNER_PATH}/python:$PYTHONPATH
```

Normal users will just have to `pip install scannerpy`, provided they have all the dependencies installed. Otherwise, they can use a Docker image.

**Comment by willcrichton** [comment]
One other note: to publish a new pip package, you need to tag a commit, e.g.

```
git commit -am "Foobar"
git tag v0.1.0
git push --tags
```

Don't forget to change the version number in `setup.py` accordingly, or the publish will fail!
