### ISSUE TITLE
Add end-to-end test for python API

### ISSUE THREAD

**Issue by apoms** [scanner-research/scanner#18]
The python API is currently untested, letting breaking changes in the C++ API cause issues with the python functionality. We should add some from of end-to-end tests and investigate unit testing functionality.

**Comment by willcrichton** [comment]
After looking through some frameworks, [pytest](http://doc.pytest.org/en/latest/) seems pretty reasonable. I added an example test in 474726782dddf34171257b9759f2804e8ef311f6 which you can run with `pytest tests` from the source root (you'll need to `pip install pytest` first).

**Comment by willcrichton** [comment]
We can always add more tests, but now we have nontrivial coverage as of 349283eb4e54f15a3759cd0a543e50fe3c9d0233.
