### ISSUE TITLE
Documentation could benefit from "Binding Model" discussion 

### ISSUE THREAD

**Issue by kayvonf** [scanner-research/scanner#181]
This seems non-trivial, but the issue has raises its head in a number of situations at this point.  So I think the docs need to get to this design issue quickly.

  -- how does one bind parameters to a graph, and when
  -- What is the motivation for the choices made. (What does it allow the runtime to do more efficiently?)

**Comment by apoms** [comment]
Updated this in the most recent commit (will take a few minutes to propagate to website). Let me know if that covers it.
