### ISSUE TITLE
Wordsmithing suggestions on "Getting Started" page.

### ISSUE THREAD

**Issue by kayvonf** [scanner-research/scanner#192]
Suggest edit to:

Once you have a handle on the basics, you can checkout Interactive Jupyter Walkthrough, which provides a more full fledged walkthrough of using Scanner in a real application, or Tutorial, which provides examples of many of the features of the API.

-->

Once you have a handle on the basics, you can checkout Interactive Jupyter Walkthrough, which provides a more full fledged walkthrough of using Scanner in a real application. Or you can take a look at the numerous Scanner [tutorials] available on github which provide examples of using key features of the Scanner API.

Then in the list below, you might consider linking directly to the github tutorials page, rather than having a separate page in the docs that does just that.  However the pitfall of this approach is that "Tutorials" won't appear in the sidebar under "Getting Started"

**Comment by apoms** [comment]
Done
