### ISSUE TITLE
Quickstart should have a multi-job section + add forward pointers to TFlow.

### ISSUE THREAD

**Issue by kayvonf** [scanner-research/scanner#200]
Just talked about this one on Skype.  I'd like the quickstart to make two points:

1. That you probably want to be running DNNs, but let's first talk about running "something".  It's too bad we couldn't have a DNN here.

2. That you probably want to run on lots of videos.  So let me show you how to run on one.  Then at the end let's talk about running on a whole directory of videos.  (Hypothetically a whole directory... might want to tell them to download a bunch of videos into a directory.)

**Comment by apoms** [comment]
Done
