### ISSUE TITLE
Is there anywhere I can read about how you schedule the work so that the usage of resources (CPU or GPU) is maximized? Must I go through the entire codebase?

### ISSUE THREAD

**Issue by yxchng** [scanner-research/scanner#202]

**Comment by ahirner** [comment]
@yxchng I've read the siggraph paper. It explains scheduling, pipelining and how graphs are distributed (across videos and scenes depending on the operations). Chapter 4: http://graphics.stanford.edu/papers/scanner/scanner_sig18.pdf

**Comment by willcrichton** [comment]
The main guide here is Section 4.1 of the paper as @ahirner cited.

More concretely, we query the machine for its resources ([defined here](https://github.com/scanner-research/scanner/blob/master/scanner/api/database.h#L30)), e.g. # of cores/GPUs/etc., then attempt to spawn as many pipelines on each machine as the resources will permit without oversubscribing. 

Right now, I think the scheduler assumes that each kernel uses 1 compute unit of the requested type (CPU/GPU), although that's not a fundamental restriction, just an artifact of our relatively simple work scheduler.
