### ISSUE TITLE
Quickstart main.py error

### ISSUE THREAD

**Issue by msharmavikram** [scanner-research/scanner#203]
##The main.py sample provided has a couple of typos. Here are the diffs to get it corrected. 

diff --git a/examples/apps/quickstart/main.py b/examples/apps/quickstart/main.py
index 64ca6ea..b1130e3 100644
--- a/examples/apps/quickstart/main.py
+++ b/examples/apps/quickstart/main.py
@@ -4,7 +4,7 @@ db = Database()
 
 # The input is formatted as a list of (table_name, video_path). 
-db.ingest_videos([('sample-clip', 'sample-clip.mp4')], force=True)
+db.ingest_videos([('table_name', 'sample-clip.mp4')], force=True)
 
  # Bind arguments to the source and sink nodes
 job = Job(op_args={
-frame: db.table(table_name).column('frame'), # Column to read input frames from
-output_frame: 'resized-{:s}'.format(table_name) # Name of output table
+frame: db.table('table_name').column('frame'), # Column to read input frames from
+output_frame: 'resized-{:s}'.format('table_name') # Name of output table
 })

**Comment by apoms** [comment]
Thanks @msharmavikram! Should be fixed in the commit linked to this issue.
