### ISSUE TITLE
How to enable profiler

### ISSUE THREAD

**Issue by msharmavikram** [scanner-research/scanner#205]
As I read the code, I see that there are a few inbuilt profilers. (Like io read time -` profiler.add_interval("io", io_start, now()); profiler.increment("io_read", static_cast<i64>(buffer_size));`) 

How do I enable these profilers and dump into a stat file? Is there a special switch I need to use? 
I am interested in io time split between loading data from disk to memory, processing of data to be stored in the table entry, reading data from the table entry, compute time, updating the table entry if needed. 

Why I need this data? This would provide me some insight on what kind of system should I consider building to use scanner and also understand if I am limited by memory or IO or compute. 

I also had another couple of questions after reading the paper. 
1. In the result section, you have described about the machine that you have used. However, the machine missed information of DRAM. What is the size of memory did the host use? ( I am expecting above 32GB but I am not sure if its about 128 or 256GB or more)
2. What is the data set size of 2.2hr, 202K frame with full HD on H.264? (> 25GB?)  This website gives me https://www.digitalrebellion.com/webapps/videocalc about 130GB. I am not sure if the size will be that huge. 

Thanks!

**Comment by willcrichton** [comment]
The profiler information can be extracted as shown in this example: https://github.com/scanner-research/scanner/blob/master/examples/tutorials/07_profiling.py

To visualize the trace, go to [chrome://tracing/](chrome://tracing/), click "Load", and select the trace file.

Right now, the system doesn't make any scheduling decisions with respect to the memory size of the system. If you look at section 4 of the paper, we talk about the knobs available for dealing with the quantity of data allowed in memory. Specifically, queue size and work packet size together determine how much data can flow through the pipeline at any point in time. Currently, you just have to tune them for your workload.

I'm not sure how big your specific dataset will be, but Scanner doesn't try to load it all into memory at once, so you don't need to worry about your dataset size.

**Comment by msharmavikram** [comment]
Thanks for the explanation. That helped. 

Since you mentioned about loading to the memory in a pipeline manner, I have a question on GPU use case, assuming we are doing an object detection in a video frame. Does Scanner currently have two copies of information, one as a table at the host and one at the GPU memory as a current frame or can the table be shared across GPU and CPU? It is not clear to me from the Figure 4 left of the graph, what is exactly done here.

**Comment by willcrichton** [comment]
For video, the way it works is the encoded video is read into CPU memory. If the first kernel in the pipeline is a GPU kernel, then we use the GPU decoder which decodes frames directly into GPU memory, which are then passed into the kernel. If the first kernel is a CPU kernel, then we use the CPU decoder. We don't duplicate data in either scenario.
