### ISSUE TITLE
Scanner on kubernetes starting on AWS

### ISSUE THREAD

**Issue by jblakley** [scanner-research/scanner#210]
Have been trying to get Scanner running with kubernetes on AWS with a KOPS created cluster. Modified the examples/apps/kubernetes to point to my container. Finally got it to starting the container which then crashes with the following error(s) from kubectl --v=8 logs <POD>   Any ideas? Need more info?

In worker:
I0618 20:49:28.085464   24490 round_trippers.go:414]     Date: Mon, 18 Jun 2018 20:49:28 GMT
Traceback (most recent call last):
  File "worker.py", line 10, in <module>
    port=5002)
TypeError: start_worker() got an unexpected keyword argument 'prefetch_table_metadata'

I0618 20:49:27.927622   24467 round_trippers.go:414]     Content-Length: 190
I0618 20:49:27.927634   24467 round_trippers.go:414]     Date: Mon, 18 Jun 2018 20:49:27 GMT
Traceback (most recent call last):
  File "master.py", line 9, in <module>
    no_workers_timeout=180)
TypeError: start_master() got an unexpected keyword argument 'prefetch_table_metadata'

**Comment by jblakley** [comment]
More info. I was able to replicate the issue on a local container using the same container image as I'm using  above. The standard scannerresearch/scanner:cpu container works just fine on this instance.

But when I do:

# to start conttainer (GCRWORKER is the image of the worker container)
docker pull $GCRWORKER
docker run -it $GCRWORKER bash

# In container
PYTHONORIG=$PYTHONPATH
export PYTHONPATH=$PYTHONORIG:/opt/scanner/python
export SCANNER_MASTER_SERVICE_HOST=foo
export SCANNER_MASTER_SERVICE_PORT=bar
python3 worker.py

I get:

Traceback (most recent call last):
  File "worker.py", line 10, in <module>
    port=5002)
TypeError: start_worker() got an unexpected keyword argument 'prefetch_table_metadata'

**Comment by apoms** [comment]
Just pushed a fix. There was an extra parameter in the ‘master.py’ and ‘worker.py’ files which I removed. 

Let me know if that fixes the problem!

**Comment by jblakley** [comment]
Alex, That fixed it. Thanks!
