### ISSUE TITLE
Is enum34 necessary?

### ISSUE THREAD

**Issue by keunhong** [scanner-research/scanner#241]
enum34 is install in the docker image, but the docker image uses Python 3.5. This clashes with the build-in enum library and breaks some packages (e.g. pipenv).

The dependency is listed here: https://github.com/scanner-research/scanner/blob/master/docker/ubuntu16.04/requirements.txt#L9

**Comment by apoms** [comment]
We don't use that anymore, thanks for pointing it out! 

Just pushed a commit with the package removed from the requirements file. The docker image should be updated in ~1 hour after the automated tests finish.
