### ISSUE TITLE
Docker image for CUDA10.0

### ISSUE THREAD

**Issue by kentaroy47** [scanner-research/scanner#259]
First of all, thanks for the great developments.
Is there a future schedule for adding docker image for CUDA10.0 as well?
Thanks.

**Comment by willcrichton** [comment]
I think the big issue is that NVCUVID was deprecated in CUDA 10 and changed into the [Video Codec SDK](https://developer.nvidia.com/nvidia-video-codec-sdk) which uses a different API and so breaks our GPU decoder. (cc @apoms who knows more)

There's nothing fundamental preventing Scanner from supporting CUDA 10, but we would need some engineering/testing to update to the new API.

**Comment by kentaroy47** [comment]
@willcrichton 
Thank you for the answers.
I got it that it will take much effort to support CUDA10, will revert to CUDA9 and use scanner.
Thanks.
