### ISSUE TITLE
'All videos failed to ingest properly' on 480p and 360p

### ISSUE THREAD

**Issue by angelamontemayor** [scanner-research/scanner#269]
I downloaded a video from youtube using a video download app (4k Video Downloader), and I selected the video quality as "High Quality" (or 480p). Upon feeding it to the [greyscale scanner tutorial](http://scanner.run/guide/walkthrough.html#walkthrough), I get the following error:

`Traceback (most recent call last):
  File "grayscale_conversion.py", line 37, in <module>
    main()
  File "grayscale_conversion.py", line 27, in main
    cl.run(output, sp.PerfParams.manual(50, 250))
  File "/usr/local/lib/python3.5/dist-packages/scannerpy/client.py", line 1336, in run
    storage.ingest(self, streams)
  File "/usr/local/lib/python3.5/dist-packages/scannerpy/storage.py", line 244, in ingest
    sc.ingest_videos(to_ingest[i:i+batch], inplace=False, force=True)
  File "/usr/local/lib/python3.5/dist-packages/scannerpy/client.py", line 1016, in ingest_videos
    raise ScannerException(ingest_result.result.msg)
scannerpy.common.ScannerException: All videos failed to ingest properly`

After changing the video to 360p, I get the same error. It only worked for me on 240p resolution. Here is the video at 480p resolution on google drive:
https://drive.google.com/file/d/11bL88z_eOOiARe87z8VnPlz9sYIOhXXM/view?usp=sharing

**Comment by willcrichton** [comment]
What do you mean by feeding it to the tutorial? `grayscale_conversion.py` assumes the existence of a file `sample-clip.mp4` in the directory you call the script.

**Comment by angelamontemayor** [comment]
Right, thats what I meant. I placed both videos (the 240p and 480p) inside of the `/opt/scanner/examples/apps/walkthroughs` directory, and I called the script separately on both of the videos, and it only produced output for the 240p video.

**Comment by willcrichton** [comment]
Can you try `rm -r ~/.scanner/db` and re-run with the 480p video? I wasn't able to reproduce the error on my machine.

**Comment by willcrichton** [comment]
Closing this for now but we can reopen if it seems like a persistent issue.
