### ISSUE TITLE
Support OSX for prototyping

### ISSUE THREAD

**Issue by apoms** [scanner-research/scanner#29]
We should allow users to run Scanner locally instead of requiring a Linux cluster to get up and running.

**Comment by willcrichton** [comment]
For prototyping locally, we should encourage people to use the Docker image. We might need to think a little bit about the Docker workflow (e.g. what commands should people run? We should give guidance on where to store files, mount volumes, etc.), but that would save us a lot of time over figuring out all the dependencies on OS X.

**Comment by apoms** [comment]
Yeah, I agree. We should just have a "Getting Started on OSX" guide that makes it easy to get everything running on a laptop.

**Comment by willcrichton** [comment]
Merging with #71
