### ISSUE TITLE
Support Scanner running inside of Docker on a cluster

### ISSUE THREAD

**Issue by apoms** [scanner-research/scanner#31]
"We also need to explore how to setup a cluster when the nodes are wrapped in Docker containers. Right now you can only use Docker for quickly experimenting on a single node, but can't use it to scale out (or at least, we haven't tried). It might Just Work™, but it might need some fussing with the Docker network configuration or god knows what else. " - Will

**Comment by willcrichton** [comment]
Closing in favor of #71
