### ISSUE TITLE
Basic Google Cloud support

### ISSUE THREAD

**Issue by willcrichton** [scanner-research/scanner#34]
Should be able to use S3 storage backend for Storehouse in conjunction with Google Compute Engine instances to run Scanner jobs. Doesn't have to be perfect (e.g. manually sshing into nodes is ok), but should allow hackathon users to run their own GPU cluster.

**Comment by apoms** [comment]
This will be awesome! Being able to spin up a bunch of nodes to churn through a large dataset would be incredibly useful.
