### ISSUE TITLE
Support producing video columns from pipelines

### ISSUE THREAD

**Issue by apoms** [scanner-research/scanner#41]
This should automatically encode the frames as video and allow export of these videos directly as an mp4 file.

**Comment by apoms** [comment]
ffmpeg has opensource h264 encoding support on CPUs using:
https://github.com/cisco/openh264

For NVIDIA, we should use the hardware encode API: 
https://developer.nvidia.com/nvidia-video-codec-sdk#NVENCFeatures

**Comment by willcrichton** [comment]
Completed with #59
