### ISSUE TITLE
Support local eager evaluation of OpDAG for debugging purposes

### ISSUE THREAD

**Issue by apoms** [scanner-research/scanner#48]
We should have a way to run the OpDAG locally without going through the Scanner runtime simply for debugging purposes.

**Comment by willcrichton** [comment]
(pursuant to my discussion with @apoms) This is also the first step towards two important ends:

1. With a standalone DAG evaluator, it's easier to implement a streaming version of Scanner that draws from online or local datasources (e.g. webcam). 
2. This will help us compartmentalize the evaluator from the decoder from the distributor. Other people I've talked to really want a high performance video decoder, so breaking that component out as well could be useful.
