### ISSUE TITLE
Cryptic error for caffe GPU kernels

### ISSUE THREAD

**Issue by jremmons** [scanner-research/scanner#65]
Hey scanner team, when I try to use a caffe kernel on multiple GPUs I get a very cryptic error when scanner cannot use one of the GPUs (i.e. it is being used by someone else).

For example, when GPU 0 is being fully utilized by another user and I try to run a scanner job which uses GPUs I get the following error:

```
...
F0418 22:11:33.232616 24726 cudnn_conv_layer.cpp:53] Check failed: status == CUDNN_STATUS_SUCCESS (4 vs. 0)  CUDNN_STATUS_INTERNAL_ERROR
*** Check failure stack trace: ***
Process Process-1:
...
```

If I run `export CUDA_VISIBLE_DEVICES=1,2,3` my code runs just fine fine though. Wasted half a day on this... Would be nice if scanner used as many of the GPUs that it could automatically without failing (maybe a warning?). Or at least output a better error message!

**Comment by willcrichton** [comment]
Agreed on a better error message. We're generally avoiding the issue of multitenancy for now, but something to address in the future.

**Comment by jremmons** [comment]
Okay, sounds good! Thanks @willcrichton
