### ISSUE TITLE
Trying to access table that does not exist

### ISSUE THREAD

**Issue by jremmons** [scanner-research/scanner#66]
I had a bug in my code where I tried to access a table that I had not yet created. The error message I got was not very helpful though...

```
Traceback (most recent call last):
  File "examples/resnet/resnet_featureizer.py", line 78, in <module>
    hdf5ify(resnet_features_db_name, output_path)
  File "examples/resnet/resnet_featureizer.py", line 56, in hdf5ify
    for i, vec in table.load(['caffe_output'], parsers.array(np.float32)):
  File "/h/jemmons/scanner/python/scannerpy/table.py", line 84, in load
    for tup in izip(*cols):
  File "/h/jemmons/scanner/python/scannerpy/column.py", line 89, in _load
    for output in self._load_output_file(item_id, select_rows, fn):
  File "/h/jemmons/scanner/python/scannerpy/column.py", line 31, in _load_output_file
    raise ScannerException('Path {} does not exist'.format(path))
scannerpy.common.ScannerException: Path /h/jemmons/.scanner_db/tables/137/1_0.bin does not exist
(
```

Also, an error was NOT raised when I created the table object, I only got an error when I tried to load data from the table. (see example below)

```
with Database() as db:
    table = db.table('non_existent_table') # no error!
    # lots of code here...
    # ...
    table.load('column_from_non_existent_table') # code explodes here!
```

Would be great if there was a check when the table object was created!

**Comment by willcrichton** [comment]
`db.table` is set to raise an exception if you try to access a table that doesn't exist. Are you sure it didn't exist when you first accessed it? (like if you `print db.summarize()` before the operations it doesn't exist?)

**Comment by jremmons** [comment]
You are right. This is an even weirder bug then. Not sure what happened, but the problem resolved itself when I reran the code that generated the table I was interested in. Maybe the output on disk got messed up? Probably my fault.

**Comment by kayvonf** [comment]
John it's awesome that you're working on the project now.  It's super
useful to have someone seriously using Scanner that wasn't involved in it's
implementation.  It's a great sanity check on the design and the
implementation!

**Comment by jremmons** [comment]
@kayvonf scanner should be a very useful tool for my research. Happy to contribute back :)

**Comment by willcrichton** [comment]
Closing this until we have a clear repro.
