### ISSUE TITLE
Add source/sinks for reading/writing external data

### ISSUE THREAD

**Issue by apoms** [scanner-research/scanner#95]
Proposal
=======
Extend Scanner with `Source`s and `Sink`s that allow the system to read or write data to locations external to the database.

Motivation
-----------
Scanner should be able to read or write data which is not just stored in our database representation. This is useful for reading data in-place (for example, a large collection of custom encoded RAW frames) or writing it to external services (such as to individually addressable objects in GCS).

Target Use Cases
------------------
* Read/write to memory
* Read/write to individual files on GCS
* Read/write to individual files on disk
* Read/write to video files

Example Code
---------------
Frame Column -> Table
```python
frame = db.sources.FrameColumn()
flow = db.ops.OpticalFlow(frame=frame)
output = db.sinks.Table(columns=[sampled_flow])
```

Frame Column -> GCS files
```python
frame = db.sources.FrameColumn()
flow = db.ops.OpticalFlow(frame=frame)
output = db.sinks.GCS(input=sampled_flow)
```

Frame Column -> Videos on GCS
```python
frame = db.sources.FrameColumn()
output = db.sinks.GCS(input=frame.compress(), entire_column=True)
```

Frame Column -> Memory
```python
frame = db.sources.FrameColumn()
pose = db.ops.OpenPose(frame=frame)
output = db.sinks.Memory(input=pose)
...
bulk_job = BulkJob(output=output, jobs=jobs)
with db.run(bulk_job) as session:
    pose, frame_id, table_name = output.pull()
```

Memory -> Table
```python
frame = db.sources.FrameMemory()
pose = db.ops.OpenPose(frame=frame)
output = db.sinks.Output(columns=[pose])
...
bulk_job = BulkJob(output=output, jobs=jobs)
with db.run(bulk_job) as session:
    frame.push(...)
```

**Comment by willcrichton** [comment]
* input/output or io instead of source/sink
* don't necessarily need db.run output to be scoped in a session, in memory outputs can just be a python iterator
* at first glance seemed like FrameColumn was describing *type* of input whereas GCS was describing *location* of output which was confusing

**Comment by swjz** [comment]
In order to support streaming mode (#104), I would like to first add support for reading data from memory to stream (table), and loading data from stream to memory.

Here is my brief proposal:
For now, I would leave most of current Python API unchanged. It should be something like this:
```python
frame = db.ops.MemoryInput()
pose = db.ops.OpenPose(frame=frame)
output = db.ops.MemoryOutput(columns=[pose])
...
bulk_job = BulkJob(output=output, jobs=jobs)
db.run(bulk_job, force=True)

frame.push(...)
output.pull(...)
```
The `frame.push()` and `output.pull()` should behave just like a queue, with some reasonable latency.

To achieve this, each input row (frame) from memory in Python should be sent to a worker in C++ via grpc:
```proto
message ElementDescriptor {
  int64 row_id = 1;
  bytes buffer = 2;
}
```
When worker receives the row buffer, it fills its own `BatchedColumns columns` object in `struct EvalWorkEntry` with the serialized buffer. 

At the same time, the master should be aware that we are dealing with a stream instead of fixed table. So no `TableMetadata` is needed anymore.

Output to memory is in a similar way. Worker saves rows to Python via grpc so that we can call `output.pull()` in Python.

**Comment by apoms** [comment]
In order to make this as forward compatible as possible, we should try to make the incremental steps integrate well with the high-level design we talked about last week. 

Specifically, since we are special casing the streaming behavior for now (bypassing the master), let's just have the worker talk directly to the client as if it was the master. This makes it so very little of the worker code needs to change. You can achieve this by implementing a subset of the master GRPC interface using python and then having the worker connect to this "python master". The specific methods would be:

```
  /// Worker registration methods
  // Called after a new worker spawns to register with the master
  rpc RegisterWorker (WorkerParams) returns (Registration) {}
  // Called when a worker is removed
  rpc UnregisterWorker (NodeInfo) returns (Empty) {}

  // Internal
  rpc NextWork (NodeInfo) returns (NewWork) {}
  rpc FinishedWork (FinishedWorkParameters) returns (Empty) {}
  rpc FinishedJob (FinishedJobParams) returns (Empty) {}
```

These are the only methods the worker calls on the master. 

In order to support passing frames, we need to address two issues. First, the worker currently receives work as packets of output rows that it needs to compute. These output row ids are used to compute which inputs are needed for producing each of those outputs. That structure is here: https://github.com/scanner-research/scanner/blob/master/scanner/engine/rpc.proto#L210-L216. However, in the streaming model, we instead want to give the worker input rows (instead of saying which output row ids should be selected) and have it produce as many outputs as it can. I think the major changes for fixing this would be to get rid of all the dependency analysis for determining input rows if in streaming mode (https://github.com/scanner-research/scanner/blob/master/scanner/engine/worker.cpp#L1477-L1486) and just push the rows into the work queue. Second, you need to modify the `NewWork` structure (https://github.com/scanner-research/scanner/blob/master/scanner/engine/rpc.proto#L210-L216)
to support more generic payloads for each row (for example, for sending frames). This way you can pass the frames from the python client given via `push()` to the worker. Perhaps something like:

```
message ElementDescriptor {
  int64 id = 1;
  bytes buffer = 2;
}

message NewWork {
  int32 table_id = 1;
  int32 job_index = 2;
  int32 task_index = 3;
  repeated ElementDescriptor rows = 4 [packed=true];
  bool wait_for_work = 5;
  bool no_more_work = 6;
```

In order to support reading frames back, you need to have the worker send data when calling `FinishedWork` (which is called here https://github.com/scanner-research/scanner/blob/master/scanner/engine/worker.cpp#L1418-L1427). This function is currently invoked whenever a task received by `NextWork` is finished. A task is finished when a save worker processes the last piece of data in that task and then pushes an indicator that the task was finished into a queue (https://github.com/scanner-research/scanner/blob/master/scanner/engine/worker.cpp#L442-L446).

To support getting data back to the python client in streaming mode, the save worker could also push data into the finished task indicator queue. Then, when the worker calls `FinishedWork`, we could fill up the `FinishedWorkParameters` with the payload in the same way we filled up the `NewWork` structure with the input data payload. Specifically, I would extend the structure (https://github.com/scanner-research/scanner/blob/master/scanner/engine/rpc.proto#L168-L173) in a similar way as above to support the worker sending more generic payloads for each output row.

The flow should go something like:

1) Python client receives frame via `push()` and puts the frames in a queue.
2) The worker invokes `NextWork` on the "python master" and the python client then pops frames from its queue and sends them to the worker via the modified `NewWork` structure.
3) The worker processes these frames and produces output data that it puts in the finished task queue.
4) The worker calls `FinishedWork` on the "python master" with the output data, which the python client then pushes into an output data queue.
5) Whenever `pull()` is called, an element from the output data queue is pop'ed off and returned.

Let me know if I can clarify anything.
